### ISSUE TITLE
document upload error

### ISSUE THREAD

**Issue by bfeldman89** [MuckRock/documentcloud#111]
I'm trying to upload a pdf from my computer to documentcloud. The code has been working for a while, but stopped working last night or this morning. 

```
>>> pdf_stuff.pdf_to_dc(quiet=False)
checking mcdc. . .
checking prcdf. . .
checking lcdc. . .
uploading output/lcdc/298987_19.pdf . . .
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/blakefeldman/code/jail_scrapers/pdf_stuff.py", line 102, in pdf_to_dc
    obj = dc.documents.upload(fn)
  File "/Users/blakefeldman/.local/share/virtualenvs/jail_scrapers-50neoEVy/lib/python3.8/site-packages/documentcloud/documents.py", line 265, in upload
    return self._upload_file(pdf, **kwargs)
  File "/Users/blakefeldman/.local/share/virtualenvs/jail_scrapers-50neoEVy/lib/python3.8/site-packages/documentcloud/documents.py", line 323, in _upload_file
    presigned_url = create_json["presigned_url"]
KeyError: 'presigned_url'
>>> 
```

**Comment by mitchelljkotler** [comment]
We switched over our URLs from https://beta.documentcloud.org to https://www.documentcloud.org yesterday.  There are redirects in place, but those do not work for uploading documents.  The best solution is to upgrade to the latest version of the library here:
https://pypi.org/project/python-documentcloud/ (we switched back to python-documentcloud).  You can also manually specify the base API URL as https://api.www.documentcloud.org/api/ when initializing the client.

**Comment by bfeldman89** [comment]
Thanks so much, @mitchelljkotler. That worked.
